In [230]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import os
import seaborn as sns
import plotly.express as px



pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
%config Completer.use_jedi = False

In [231]:
ae = pd.read_csv("adae_pds2019.csv")

In [232]:
adrsp = pd.read_csv("adrsp_pds2019.csv")

In [233]:
adsl = pd.read_csv("adsl_pds2019.csv")

In [234]:
adlb = pd.read_csv("adlb_pds2019.csv")

In [235]:
adls = pd.read_csv("adls_pds2019.csv")

In [236]:
ae['AESOC'].unique()

array(['Skin and subcutaneous tissue disorders',
       'Infections and infestations',
       'Injury, poisoning and procedural complications',
       'General disorders and administration site conditions',
       'Vascular disorders',
       'Neoplasms benign, malignant and unspecified (incl cysts and polyps)',
       'Hepatobiliary disorders',
       'Reproductive system and breast disorders',
       'Gastrointestinal disorders',
       'Respiratory, thoracic and mediastinal disorders',
       'Blood and lymphatic system disorders'], dtype=object)

In [237]:
ae['Duration'] = ae['AEENDYI'] - ae['AESTDYI']

In [238]:
adae_df = ae[['SUBJID', 'AEPT','AESOC','AESEVCD','Duration']]

In [239]:
df_one_hot = pd.get_dummies(adae_df, columns=['AESOC'], prefix='AESOC')

# Group by SUBJID and AEPT, summing the one-hot encoded columns
adae_df = df_one_hot.groupby(['SUBJID'], as_index=False).sum()

In [240]:
adae_df

SUBJID                                               AEPT  AESEVCD  Duration  AESOC_Blood and lymphatic system disorders  AESOC_Gastrointestinal disorders  AESOC_General disorders and administration site conditions  AESOC_Hepatobiliary disorders  AESOC_Infections and infestations  AESOC_Injury, poisoning and procedural complications  AESOC_Neoplasms benign, malignant and unspecified (incl cysts and polyps)  AESOC_Reproductive system and breast disorders  AESOC_Respiratory, thoracic and mediastinal disorders  AESOC_Skin and subcutaneous tissue disorders  AESOC_Vascular disorders
0         3           Dermatitis acneiformDermatitis acneiform      2.0      33.0                                           0                                 0                                                  0                                       0                                  0                                                  0                                                     0                                                                       0                                                  0                                                 2                         0
1         7  RashRashRashRashRashFuruncleFolliculitisFollic...     14.0     308.0                                           0                                 0                                                  0                                       0                                  3                                                  0                                                     0                                                                       0                                                  0                                                 5                         0
2         9  Exfoliative rashExfoliative rashDermatitis acn...     17.0     219.0                                           0                                 0                                                  0                                       0                                  0                                                  0                                                     0                                                                       0                                                  0                                                14                         0
3        13                                       RashRashRash      4.0      74.0                                           0                                 0                                                  0                                       0                                  0                                                  0                                                     0                                                                       0                                                  0                                                 3                         0
4        15  PruritusDry skinDermatitis acneiformDry skinPa...     12.0     214.0                                           0                                 0                                                  0                                       0                                  1                                                  0                                                     0                                                                       0                                                  0                                                 7                         0
..      ...                                                ...      ...       ...                                         ...                               ...                                                ...                                     ...                                ...                                                ...                                                   ...                                                                     ...   

In [241]:
# Assuming 'AESOC' columns start after the 5th column in the grouped DataFrame
start_index = 4

# Create a dictionary mapping old column names to new ones, starting from AESOC_1
new_column_names = {col: f'AESOC_{i+1}' for i, col in enumerate(adae_df.columns[start_index:]) if col.startswith('AESOC')}

# Rename the columns using the created dictionary
adae_df.rename(columns=new_column_names, inplace=True)



In [242]:
new_column_names

{'AESOC_Blood and lymphatic system disorders': 'AESOC_1',
 'AESOC_Gastrointestinal disorders': 'AESOC_2',
 'AESOC_General disorders and administration site conditions': 'AESOC_3',
 'AESOC_Hepatobiliary disorders': 'AESOC_4',
 'AESOC_Infections and infestations': 'AESOC_5',
 'AESOC_Injury, poisoning and procedural complications': 'AESOC_6',
 'AESOC_Neoplasms benign, malignant and unspecified (incl cysts and polyps)': 'AESOC_7',
 'AESOC_Reproductive system and breast disorders': 'AESOC_8',
 'AESOC_Respiratory, thoracic and mediastinal disorders': 'AESOC_9',
 'AESOC_Skin and subcutaneous tissue disorders': 'AESOC_10',
 'AESOC_Vascular disorders': 'AESOC_11'}

In [243]:
adae_df

SUBJID                                               AEPT  AESEVCD  Duration  AESOC_1  AESOC_2  AESOC_3  AESOC_4  AESOC_5  AESOC_6  AESOC_7  AESOC_8  AESOC_9  AESOC_10  AESOC_11
0         3           Dermatitis acneiformDermatitis acneiform      2.0      33.0        0        0        0        0        0        0        0        0        0         2         0
1         7  RashRashRashRashRashFuruncleFolliculitisFollic...     14.0     308.0        0        0        0        0        3        0        0        0        0         5         0
2         9  Exfoliative rashExfoliative rashDermatitis acn...     17.0     219.0        0        0        0        0        0        0        0        0        0        14         0
3        13                                       RashRashRash      4.0      74.0        0        0        0        0        0        0        0        0        0         3         0
4        15  PruritusDry skinDermatitis acneiformDry skinPa...     12.0     214.0        0        0        0        0        1        0        0        0        0         7         0
..      ...                                                ...      ...       ...      ...      ...      ...      ...      ...      ...      ...      ...      ...       ...       ...
603    1169                   RashRashRashRashRashRashRashRash     14.0     180.0        0        0        0        0        0        0        0        0        0         8         0
604    1171  Dermatitis acneiformDermatitis acneiformDermat...      9.0     209.0        0        0        0        0        1        0        0        0        0         5         0
605    1172                           AcneAcneDry skinDry skin      9.0     130.0        0        0        0        0        0        0        0        0        0         4         0
606    1181  PruritusAcneDry skinAcneSkin hyperpigmentation...     28.0     586.0        0        0        0        0        0        0        0        0        0        18         0
607    1182  AcrodermatitisDermatitisSkin exfoliationSkin e...     26.0     395.0        0        0        0        0        0        0        0        0        0        19         0

[608 rows x 15 columns]

In [244]:
adae_df.nunique()

SUBJID      608
AEPT        420
AESEVCD      39
Duration    327
AESOC_1       2
AESOC_2       2
AESOC_3       4
AESOC_4       4
AESOC_5       9
AESOC_6       3
AESOC_7       3
AESOC_8       2
AESOC_9       2
AESOC_10     29
AESOC_11      6
dtype: int64

In [245]:
adae_df.shape

(608, 15)

In [246]:
adrsp_df = adrsp[['SUBJID','RSRESP']]

In [247]:
adrsp_df['RSRESP'].unique()

array([nan, 'Stable disease', 'Progressive disease', 'Partial response',
       'Unable to evaluate', 'Complete response'], dtype=object)

In [248]:
adrsp_df = adrsp_df.drop_duplicates(keep = 'first')

In [249]:
adrsp_df = adrsp_df.dropna()

df_one_hot = pd.get_dummies(adrsp_df, columns=['RSNEW'], prefix='RSNEW')

grouped = df_one_hot.groupby(['SUBJID', 'RSRESP'], as_index=False).sum()

grouped

In [250]:
df_one_hot = pd.get_dummies(adrsp_df, columns=['RSRESP'], prefix='RSRESP')

# Group by SUBJID and AEPT, summing the one-hot encoded columns
adrsp_df = df_one_hot.groupby(['SUBJID'], as_index=False).sum()

In [251]:
adrsp_df = adrsp_df.drop_duplicates(keep = 'first')

In [252]:
adrsp_df.drop_duplicates(subset=['SUBJID'], inplace=True)


In [253]:
adrsp_df.shape

(902, 6)

boolean = adrsp_df['SUBJID'].duplicated().any()


df = adrsp_df

if boolean:
    duplicated_values = df[df['SUBJID'].duplicated(keep=False)]
    print("Duplicated Subject IDs:")
    print(duplicated_values)
else:
    print("No duplicate values found in the 'Subject ID' column.")


In [254]:
adsl_df = adsl[['SUBJID', 'TRT','PRSURG', 'DTHDY', 'PFSDYCR', 'PFSCR', 'LIVERMET',  'DIAGMONS',  'B_ECOG', 'HISSUBTY', 'B_METANM', 'DIAGTYPE']]

In [255]:
adsl_df.shape

(935, 12)

In [256]:
adlb_df = adlb[['SUBJID','LBSTRESN','LBBASE']]

In [257]:
adlb_df = adlb_df.groupby(['SUBJID', 'LBBASE'])['LBSTRESN'].mean().reset_index()

In [258]:
adlb_df = adlb_df[adlb_df['LBBASE'] != 'Y'].drop(columns=['LBBASE'])


In [259]:
adlb_df.shape


(935, 2)

In [260]:
adls = pd.read_csv("adls_pds2019.csv") #LSNEW - y, LSSLD - NaN

In [261]:
adls_df = adls.groupby(['SUBJID','LSCAT','LSNEW'])['LSSLD'].mean().reset_index()

In [262]:
df_one_hot = pd.get_dummies(adls_df, columns=['LSCAT'], prefix='LSCAT')

# Group by SUBJID and AEPT, summing the one-hot encoded columns
adls_df = df_one_hot.groupby(['SUBJID', 'LSNEW','LSSLD'], as_index=False).sum()

In [263]:
adls_df = adls_df[['SUBJID','LSSLD','LSCAT_New lesion','LSCAT_Non-target lesion','LSCAT_Target lesion']]

In [264]:
adls_df.shape

(488, 5)

In [265]:
merged_df = pd.merge(adae_df,adrsp_df , on='SUBJID', how='inner')

In [266]:
merged_df.shape

(594, 20)

In [267]:
merged_df = pd.merge(merged_df,adsl_df , on='SUBJID', how='inner')

In [268]:
merged_df.shape

(594, 31)

In [269]:
merged_df = pd.merge(merged_df, adls_df, on='SUBJID', how='inner')

In [270]:
merged_df.shape

(303, 35)

In [271]:
df = pd.merge(merged_df, adlb_df, on='SUBJID', how='inner')

In [272]:
df.shape

(303, 36)

In [273]:
df.to_csv('df.csv')

# Linera Regression

## AESOC_1	

In [274]:
# for all 4 sev
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [275]:
numeric_columns = df.select_dtypes(include=['float64', 'int64']).columns

In [276]:
numeric_columns = df[numeric_columns]

In [277]:
numeric_columns

SUBJID  AESEVCD  Duration  AESOC_1  AESOC_2  AESOC_3  AESOC_4  AESOC_5  AESOC_6  AESOC_7  AESOC_8  AESOC_9  AESOC_10  AESOC_11  RSRESP_Complete response  RSRESP_Partial response  RSRESP_Progressive disease  RSRESP_Stable disease  RSRESP_Unable to evaluate   DTHDY  PFSDYCR  PFSCR   DIAGMONS  B_METANM       LSSLD  LSCAT_New lesion  LSCAT_Non-target lesion  LSCAT_Target lesion    LBSTRESN
0         3      2.0      33.0        0        0        0        0        0        0        0        0        0         2         0                         0                        0                           1                      0                          0   301.0     54.0    1.0   1.868852       5.0   99.000000                 0                        0                    1  146.679111
1         7     14.0     308.0        0        0        0        0        3        0        0        0        0         5         0                         0                        1                           0                      0                          1   339.0    339.0    1.0   2.786885       3.0  284.575342                 0                        0                    1  139.823026
2         9     17.0     219.0        0        0        0        0        0        0        0        0        0        14         0                         0                        1                           1                      1                          0   696.0    301.0    1.0  75.704918       4.0   44.071429                 0                        0                    1  119.869975
3        13      4.0      74.0        0        0        0        0        0        0        0        0        0         3         0                         0                        0                           1                      0                          0   197.0     73.0    1.0   2.032787       6.0  207.454545                 0                        0                    1  215.076154
4        15     12.0     214.0        0        0        0        0        1        0        0        0        0         7         0                         0                        1                           0                      1                          0   414.0    414.0    1.0   3.803279       2.0   97.041667                 0                        0                    1   84.785176
5        17      2.0       0.0        0        0        0        0        0        0        0        0        0         1         0                         1                        1                           0                      0                          1  1043.0    226.0    0.0   3.147541       2.0   40.416667                 0                        0                    1   84.793130
6        20      5.0     120.0        0        0        0        0        0        0        0        0        0         4         0                         0                        0                           1                      0                          0   167.0     56.0    1.0   3.639344       2.0  117.600000                 0                        0                    1  139.018000
7        24      3.0      14.0        0        0        0        0        1        0        0        0        0         0         0                         0                        1                           1                      1                          1   508.0    306.0    1.0  22.065574       1.0   54.153846                 0                        0                    1  119.647255
8        25      1.0      70.0        0        0        0        0        0        0        0        0        0         1         0                         0                        0                           0                      1                          0   724.0    724.0    1.0   1.081967       3.0  166.111111                 0                        0                    1  145.810196
9        27      1.0       0.0        0        0        0        

In [278]:
numeric_columns = numeric_columns.dropna()

In [279]:
numeric_columns.shape

(297, 29)

In [280]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_1']

In [281]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [282]:
# Create a linear regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

LinearRegression()

In [283]:
y_pred= model.predict(X_test)

In [284]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"Root Mean Squared Error: {rmse}")

Mean Squared Error: 0.0007144095868247546
Root Mean Squared Error: 0.0267284415337811


In [285]:
# Print model coefficients
print(f"Intercept: {model.intercept_}")
print(f"Coefficients: {model.coef_}")

Intercept: -0.045677243849258684
Coefficients: [ 1.55845455e-05 -2.26170128e-02 -2.55106179e-03  1.23567130e-02
 -2.08847560e-02 -1.48327721e-02  3.40972539e-05  2.78223009e-05
  1.31617330e-02 -1.67045332e-04  5.48010884e-03  8.48529331e-05
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.71120877e-05]


In [286]:
print(f"Coefficients: {model.coef_}")

Coefficients: [ 1.55845455e-05 -2.26170128e-02 -2.55106179e-03  1.23567130e-02
 -2.08847560e-02 -1.48327721e-02  3.40972539e-05  2.78223009e-05
  1.31617330e-02 -1.67045332e-04  5.48010884e-03  8.48529331e-05
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.71120877e-05]


In [287]:
y_pred

array([ 0.01900452,  0.00826778,  0.02708275,  0.01680535, -0.03623654,
        0.02609478,  0.01769102, -0.00301375, -0.04009992, -0.0590213 ,
        0.03512186,  0.03579124,  0.01966338,  0.02744419,  0.01511883,
        0.06734082,  0.00548622, -0.03439054,  0.0351075 , -0.00345495,
        0.02143419, -0.04362588, -0.0207756 ,  0.03552861,  0.03886937,
        0.0252341 ,  0.03509383,  0.04681748, -0.01339293,  0.00776793,
        0.00221056,  0.04097922,  0.00376922,  0.00307413, -0.03505531,
        0.02986653, -0.00741398,  0.01885779,  0.00657387,  0.02149866,
        0.05083253,  0.02795255,  0.0011247 ,  0.00837295,  0.04211467,
       -0.00179873, -0.02028914,  0.01671555, -0.02240163, -0.00115105,
        0.01166087,  0.01877275, -0.00055078,  0.01272666,  0.00451361,
        0.00907626,  0.02053621, -0.00768436, -0.0029838 , -0.02955738])

AESOC_1 = df[['SUBJID','AESOC_1','AESOC_1_MSE']]

AESOC_1

AESOC_1.to_csv("Change_in_AESOC_1.csv")

## AESOC_2

In [288]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_2']

In [289]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [290]:
# Create a linear regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

LinearRegression()

In [291]:
y_pred = model.predict(X_test)

In [292]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"Root Mean Squared Error: {rmse}")

Mean Squared Error: 8.745382063174187e-05
Root Mean Squared Error: 0.00935167475010449


In [293]:
# Print model coefficients
print(f"Intercept: {model.intercept_}")
print(f"Coefficients: {model.coef_}")

Intercept: -0.019811871603966563
Coefficients: [-6.30776506e-06 -3.73996310e-03  8.28933227e-03  5.98573471e-03
  1.21935984e-02 -4.43024209e-03  8.60394355e-06 -6.20820689e-06
  3.79494171e-03 -1.18376224e-04  2.08581894e-03 -4.71676406e-05
  0.00000000e+00  0.00000000e+00  0.00000000e+00  4.63820633e-05]


In [294]:
print(f"Coefficients: {model.coef_}")

Coefficients: [-6.30776506e-06 -3.73996310e-03  8.28933227e-03  5.98573471e-03
  1.21935984e-02 -4.43024209e-03  8.60394355e-06 -6.20820689e-06
  3.79494171e-03 -1.18376224e-04  2.08581894e-03 -4.71676406e-05
  0.00000000e+00  0.00000000e+00  0.00000000e+00  4.63820633e-05]


In [295]:
y_pred

array([ 0.00705162, -0.00761652, -0.00316696,  0.00200415, -0.00640355,
        0.0264281 ,  0.00487587,  0.01045383,  0.01306847,  0.00653295,
       -0.00432959,  0.00665873, -0.00848281,  0.00033631, -0.01547446,
        0.01468178,  0.01042256,  0.01285936,  0.00336798,  0.00549327,
       -0.00100775,  0.00568689,  0.00913187,  0.008254  , -0.00808445,
       -0.00070257,  0.00586261, -0.00192869,  0.00730515,  0.01221378,
       -0.00244592,  0.00693231, -0.00315109,  0.0089756 ,  0.01081016,
        0.00748779,  0.01604826,  0.00522927, -0.00010386,  0.02292358,
        0.0125621 , -0.00232381, -0.00493701,  0.02317225,  0.010386  ,
       -0.00188606, -0.00400292, -0.01081093,  0.00363139, -0.00766493,
        0.0005444 , -0.01700403, -0.00249731, -0.00504427,  0.00022003,
       -0.00325754,  0.00846455,  0.00705654, -0.0044263 ,  0.00098825])

## AESOC_3

In [296]:
numeric_columns.shape

(297, 29)

In [297]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_3']

In [298]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [299]:
# Create a linear regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

LinearRegression()

In [300]:
y_pred = model.predict(X_test)

In [301]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"Root Mean Squared Error: {rmse}")

Mean Squared Error: 0.09501520850430692
Root Mean Squared Error: 0.30824537061293705


In [302]:
# Print model coefficients
print(f"Intercept: {model.intercept_}")
print(f"Coefficients: {model.coef_}")

Intercept: 0.2686192674777491
Coefficients: [-1.14176936e-04 -6.32048047e-02  1.40145719e-02  7.11274645e-02
  2.72706658e-02  1.28129587e-01 -1.19320595e-04  2.07730784e-04
 -1.71091903e-01  1.49346310e-04 -8.60322853e-04 -1.07037064e-04
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.95993037e-04]


In [303]:
print(f"Coefficients: {model.coef_}")

Coefficients: [-1.14176936e-04 -6.32048047e-02  1.40145719e-02  7.11274645e-02
  2.72706658e-02  1.28129587e-01 -1.19320595e-04  2.07730784e-04
 -1.71091903e-01  1.49346310e-04 -8.60322853e-04 -1.07037064e-04
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.95993037e-04]


In [304]:
y_pred

array([ 0.09781608, -0.03062325,  0.10732358,  0.05215985,  0.23743856,
        0.06245292,  0.01382456,  0.11956896,  0.09886065, -0.06561858,
       -0.01496239,  0.06947328,  0.03739135, -0.03629857,  0.08122131,
        0.00228171,  0.02373397,  0.13060507, -0.05276083,  0.04489239,
        0.00190751,  0.00798124,  0.09218841,  0.05490069,  0.10535942,
        0.13191399,  0.03053127,  0.02912975,  0.08178046, -0.02933916,
        0.06055175, -0.00084357,  0.08320362,  0.05464688,  0.29950403,
        0.11808267,  0.0910235 ,  0.06806735,  0.23436164,  0.13325655,
        0.12888895,  0.08328263,  0.01421919,  0.08380608,  0.12344146,
        0.05296729,  0.06281023, -0.01798541,  0.17112976,  0.1694533 ,
        0.07154834, -0.09188597, -0.01201935, -0.06786274,  0.03302738,
        0.08931639,  0.06280631,  0.10249284,  0.10316463,  0.0070686 ])

## AESOC_4

In [305]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_4']

In [306]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [307]:
# Create a linear regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

LinearRegression()

In [308]:
y_pred = model.predict(X_test)

In [309]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"Root Mean Squared Error: {rmse}")

Mean Squared Error: 0.01889411326620151
Root Mean Squared Error: 0.13745585933746698


In [310]:
# Print model coefficients
print(f"Intercept: {model.intercept_}")
print(f"Coefficients: {model.coef_}")

Intercept: -0.014665302875234383
Coefficients: [-1.16116258e-05  1.44157781e-02 -1.89267591e-02  3.09819227e-02
  2.41465852e-02 -1.44425004e-02 -1.90527390e-06  1.83791866e-05
 -2.80619470e-02 -4.84275070e-04  9.82206951e-03  3.44243114e-04
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.39662317e-04]


In [311]:
print(f"Coefficients: {model.coef_}")

Coefficients: [-1.16116258e-05  1.44157781e-02 -1.89267591e-02  3.09819227e-02
  2.41465852e-02 -1.44425004e-02 -1.90527390e-06  1.83791866e-05
 -2.80619470e-02 -4.84275070e-04  9.82206951e-03  3.44243114e-04
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.39662317e-04]


In [312]:
y_pred

array([-0.04564432,  0.01751595,  0.07003397, -0.00046403, -0.01145907,
        0.01760067,  0.02534304, -0.00466019, -0.02431382, -0.03812583,
        0.05678628,  0.01032563,  0.11418249,  0.04578457,  0.07338448,
        0.0256295 ,  0.04297306,  0.0117943 ,  0.03006912,  0.00977861,
       -0.01549804,  0.00805596,  0.01708614,  0.00828366,  0.01780203,
       -0.03880883, -0.03642748,  0.08758163,  0.07954683,  0.01572815,
        0.00848317, -0.02521943,  0.04813406,  0.05741728, -0.01552239,
        0.00820116,  0.00802062,  0.00351665,  0.0470325 ,  0.05942668,
       -0.00189775, -0.0461597 ,  0.02278162,  0.01239859, -0.0094333 ,
       -0.04254681, -0.01458836,  0.16872486,  0.00441439, -0.0280449 ,
        0.02075887,  0.04133079, -0.02106923,  0.02344832,  0.07376891,
       -0.04856967,  0.0090937 ,  0.0117701 ,  0.0276826 , -0.01471277])

## AESOC_5

In [313]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_5']

In [314]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [315]:
# Create a linear regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

LinearRegression()

In [316]:
y_pred = model.predict(X_test)

In [317]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"Root Mean Squared Error: {rmse}")

Mean Squared Error: 0.11721753998583373
Root Mean Squared Error: 0.3423704718369178


In [318]:
# Print model coefficients
print(f"Intercept: {model.intercept_}")
print(f"Coefficients: {model.coef_}")

Intercept: 0.12739245391530526
Coefficients: [-2.18488190e-04 -3.15322292e-01  6.60726803e-02 -5.07809194e-02
  2.02706874e-01  4.19064407e-03  1.47941276e-04  1.67864685e-04
  1.97421164e-01  4.14879364e-04 -5.79616965e-02 -1.76656242e-04
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -5.20338285e-04]


In [319]:
print(f"Coefficients: {model.coef_}")

Coefficients: [-2.18488190e-04 -3.15322292e-01  6.60726803e-02 -5.07809194e-02
  2.02706874e-01  4.19064407e-03  1.47941276e-04  1.67864685e-04
  1.97421164e-01  4.14879364e-04 -5.79616965e-02 -1.76656242e-04
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -5.20338285e-04]


In [320]:
y_pred

array([ 0.20745836, -0.18839477,  0.53019159,  0.09751675, -0.09501915,
        0.49243018,  0.21190725,  0.33051714,  0.45141672,  0.13833478,
       -0.20641024,  0.2635169 ,  0.28656121, -0.02610567,  0.13517391,
       -0.04755792,  0.08766217,  0.26595716, -0.16276522,  0.22480019,
        0.10643872,  0.22262192,  0.242855  ,  0.31214347, -0.04511352,
        0.11482289,  0.08243701, -0.251049  ,  0.25613502,  0.2630075 ,
       -0.05575879,  0.1966503 , -0.01074697,  0.28347792,  0.54764913,
        0.19123239,  0.432282  ,  0.17851555,  0.34750053,  0.27274783,
        0.20573168,  0.42235428,  0.21404844,  0.49416314,  0.65031566,
       -0.03155234, -0.14593078,  0.03025345,  0.22273014,  0.15876634,
        0.1029814 , -0.14254347, -0.05491866, -0.2840359 ,  0.16413285,
       -0.10903666,  0.25440925,  0.20020085,  0.09624488,  0.22074568])

## AESOC_6

In [321]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_6']

In [322]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [323]:
# Create a linear regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

LinearRegression()

In [324]:
y_pred = model.predict(X_test)

In [325]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"Root Mean Squared Error: {rmse}")

Mean Squared Error: 0.04581694895773358
Root Mean Squared Error: 0.21404894056671614


In [326]:
# Print model coefficients
print(f"Intercept: {model.intercept_}")
print(f"Coefficients: {model.coef_}")

Intercept: 0.08590742932048022
Coefficients: [ 1.94861317e-05  1.16654411e-01  6.67264070e-02 -2.58541991e-02
  3.02603422e-02  1.36113458e-02 -7.28988368e-05 -6.98646521e-05
  4.54508425e-03 -2.18216487e-04 -7.57458730e-03 -1.37777698e-05
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.29693371e-04]


In [327]:
print(f"Coefficients: {model.coef_}")

Coefficients: [ 1.94861317e-05  1.16654411e-01  6.67264070e-02 -2.58541991e-02
  3.02603422e-02  1.36113458e-02 -7.28988368e-05 -6.98646521e-05
  4.54508425e-03 -2.18216487e-04 -7.57458730e-03 -1.37777698e-05
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.29693371e-04]


In [328]:
y_pred

array([ 0.0173703 , -0.02755387, -0.05731786,  0.04839913,  0.15553867,
        0.00446524, -0.05561186,  0.03743484,  0.09430899,  0.01992411,
        0.06669348, -0.0123274 , -0.01176952, -0.05692463,  0.00385146,
       -0.04030022,  0.0924839 ,  0.02078699,  0.0286148 ,  0.00136833,
        0.05581584,  0.02813151, -0.01431899, -0.00313017,  0.0138854 ,
        0.02318079, -0.03198271,  0.06006184, -0.00442816,  0.06098896,
        0.00249574,  0.01349721, -0.01148274,  0.06031316,  0.07663492,
        0.00260618,  0.06323245,  0.02153324, -0.04615719,  0.0170391 ,
       -0.04189336, -0.00468847,  0.03339161,  0.02235451, -0.02778408,
        0.02852689,  0.12965864,  0.00925682,  0.0403651 ,  0.07290207,
        0.05439701,  0.11155194,  0.1063036 , -0.02005676,  0.01971041,
        0.06369493,  0.00814691,  0.07508987, -0.00059361,  0.06358515])

## AESOC_7

In [329]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_7']

In [330]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [331]:
# Create a linear regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

LinearRegression()

In [332]:
y_pred = model.predict(X_test)

In [333]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"Root Mean Squared Error: {rmse}")

Mean Squared Error: 0.014133638410768295
Root Mean Squared Error: 0.11888497975256712


In [334]:
# Print model coefficients
print(f"Intercept: {model.intercept_}")
print(f"Coefficients: {model.coef_}")

Intercept: 0.03139751403984824
Coefficients: [ 2.68824515e-05 -2.64710683e-02 -3.87996923e-03 -6.96916280e-06
 -1.71988248e-02 -1.65191667e-02  1.26488398e-05  2.16331993e-05
 -6.16386405e-02 -2.29963534e-04  5.78962915e-03  1.96596399e-05
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -8.37774891e-06]


In [335]:
print(f"Coefficients: {model.coef_}")

Coefficients: [ 2.68824515e-05 -2.64710683e-02 -3.87996923e-03 -6.96916280e-06
 -1.71988248e-02 -1.65191667e-02  1.26488398e-05  2.16331993e-05
 -6.16386405e-02 -2.29963534e-04  5.78962915e-03  1.96596399e-05
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -8.37774891e-06]


In [336]:
y_pred

array([-0.0032452 ,  0.00775127,  0.00636364,  0.0052809 ,  0.01400579,
       -0.00161338, -0.00284953,  0.05855289, -0.03370875, -0.02836853,
        0.02747966,  0.00890128,  0.004167  ,  0.0107241 , -0.00927835,
        0.04768701,  0.00500443, -0.03061706,  0.02695742,  0.00502764,
        0.01060185, -0.02692936,  0.04717712,  0.00366613,  0.10120065,
        0.00429571,  0.0352891 ,  0.03398363, -0.02560502, -0.00048179,
        0.00125884,  0.02054574, -0.00592343, -0.00121959, -0.05337789,
        0.01027602, -0.01962501,  0.00111859,  0.06650484,  0.00424842,
        0.02912739,  0.01667899,  0.00615737, -0.01333664,  0.02570166,
        0.07101785,  0.03896228, -0.00292055, -0.026253  , -0.00492779,
       -0.00248344,  0.02129723,  0.01112334,  0.02045413, -0.00498762,
        0.02051947, -0.00467116,  0.06270642, -0.01449697, -0.01137064])

## AESOC_8

In [337]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_8']

In [338]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [339]:
# Create a linear regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

LinearRegression()

In [340]:
y_pred = model.predict(X_test)

In [341]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"Root Mean Squared Error: {rmse}")

Mean Squared Error: 0.0
Root Mean Squared Error: 0.0


In [342]:
# Print model coefficients
print(f"Intercept: {model.intercept_}")
print(f"Coefficients: {model.coef_}")

Intercept: 0.0
Coefficients: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [343]:
print(f"Coefficients: {model.coef_}")

Coefficients: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [344]:
y_pred

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

## AESOC_9

In [345]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_9']

In [346]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [347]:
# Create a linear regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

LinearRegression()

In [348]:
y_pred = model.predict(X_test)

In [349]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"Root Mean Squared Error: {rmse}")

Mean Squared Error: 0.016666666666666666
Root Mean Squared Error: 0.12909944487358055


In [350]:
# Print model coefficients
print(f"Intercept: {model.intercept_}")
print(f"Coefficients: {model.coef_}")

Intercept: 0.0
Coefficients: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [351]:
print(f"Coefficients: {model.coef_}")

Coefficients: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [352]:
y_pred

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

## AESOC_10

In [353]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_10']

In [354]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [355]:
# Create a linear regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

LinearRegression()

In [356]:
y_pred = model.predict(X_test)

In [357]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"Root Mean Squared Error: {rmse}")

Mean Squared Error: 17.54417634797212
Root Mean Squared Error: 4.1885768881533165


In [358]:
# Print model coefficients
print(f"Intercept: {model.intercept_}")
print(f"Coefficients: {model.coef_}")

Intercept: 0.4321881038247999
Coefficients: [ 1.50078728e-03 -4.48314755e-01 -3.67840426e-01  1.25733754e+00
 -4.00332245e-01  1.14366308e+00  3.28839517e-04  4.09895304e-03
  2.81828528e-01  1.83727207e-02  3.05505459e-01 -4.65832900e-04
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.51429446e-03]


In [359]:
print(f"Coefficients: {model.coef_}")

Coefficients: [ 1.50078728e-03 -4.48314755e-01 -3.67840426e-01  1.25733754e+00
 -4.00332245e-01  1.14366308e+00  3.28839517e-04  4.09895304e-03
  2.81828528e-01  1.83727207e-02  3.05505459e-01 -4.65832900e-04
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.51429446e-03]


In [360]:
y_pred

array([5.41340348, 4.54639401, 5.12631012, 4.02094629, 2.57616301,
       4.40578712, 6.44890241, 3.20388615, 1.59506921, 1.30960919,
       4.75993649, 4.63436914, 3.81125047, 3.62478988, 2.92807821,
       6.85532237, 4.35890522, 2.67901331, 4.77273861, 4.39370145,
       4.26866111, 1.18945548, 1.37782602, 3.96124654, 5.09341422,
       7.12880362, 6.47085987, 5.22420135, 2.41494557, 4.01828557,
       3.72953334, 5.138086  , 2.96387141, 3.20996919, 4.30869584,
       4.98046697, 3.31686228, 3.88102252, 4.4392203 , 5.08496976,
       6.80422586, 5.22861671, 4.45391981, 3.72040279, 7.3577064 ,
       2.96993006, 2.11175   , 3.26143964, 4.86977839, 4.74723116,
       3.32701562, 2.97829351, 2.77376149, 4.39133633, 3.89219588,
       6.34682049, 3.25890155, 2.698941  , 2.69840692, 2.54516648])

## AESOC_11

In [361]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_11']

In [362]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [363]:
# Create a linear regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

LinearRegression()

In [364]:
y_pred = model.predict(X_test)

In [365]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"Root Mean Squared Error: {rmse}")

Mean Squared Error: 0.29738349778133577
Root Mean Squared Error: 0.5453287978654123


In [366]:
# Print model coefficients
print(f"Intercept: {model.intercept_}")
print(f"Coefficients: {model.coef_}")

Intercept: 0.13196788375857096
Coefficients: [-2.19024858e-05  4.70818930e-02 -1.74039933e-02  7.74673655e-02
 -2.40468522e-02  2.82737206e-02 -1.02692178e-04  1.54041711e-04
 -7.47173756e-02 -4.77587702e-04 -1.10265641e-02  2.91034381e-05
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -6.97937115e-05]


In [367]:
print(f"Coefficients: {model.coef_}")

Coefficients: [-2.19024858e-05  4.70818930e-02 -1.74039933e-02  7.74673655e-02
 -2.40468522e-02  2.82737206e-02 -1.02692178e-04  1.54041711e-04
 -7.47173756e-02 -4.77587702e-04 -1.10265641e-02  2.91034381e-05
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -6.97937115e-05]


In [368]:
y_pred

array([ 0.01411508,  0.04297106,  0.04896881,  0.06395299,  0.08895453,
       -0.02834827, -0.04616833, -0.04032177, -0.0105606 , -0.01844423,
        0.0430134 ,  0.05544921,  0.01660127,  0.02116593,  0.11097113,
       -0.01169683,  0.02901134,  0.0765562 ,  0.00670432, -0.01483711,
        0.05501298, -0.00514779, -0.03657378,  0.02577316,  0.03299694,
        0.02782858, -0.01463948,  0.03450843,  0.06192983,  0.00850582,
        0.07511513,  0.01392787,  0.08743946, -0.02075719,  0.08764485,
        0.07557346,  0.04440776,  0.06017426,  0.07332846,  0.02326417,
        0.07093778,  0.05546325, -0.01069512,  0.00642686,  0.03580925,
       -0.0187557 ,  0.07538866,  0.06653155,  0.06318363,  0.03888757,
        0.07419038, -0.01690456, -0.02402688,  0.05439941,  0.0540036 ,
       -0.00573   ,  0.03763834, -0.02020076,  0.09568531, -0.00669705])

# XGBoost Regression

In [369]:
import xgboost as xgb

In [370]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

from sklearn.ensemble import GradientBoostingRegressor

import xgboost

In [371]:
SEED = 2222
EARLY_STOP_NUM = 8

In [372]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_1']

In [373]:
y

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     0
38     0
39     0
40     0
41     0
42     0
43     0
44     0
45     0
46     0
47     0
49     0
50     0
51     0
52     0
53     0
54     0
55     0
56     0
57     0
58     0
59     0
60     0
61     0
62     0
63     0
64     0
65     0
66     0
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     0
76     0
77     0
78     0
79     0
80     0
81     0
82     0
83     0
84     0
85     0
86     0
87     0
88     0
89     0
90     0
91     0
92     0
93     0
94     0
95     0
96     0
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
111    0
112    0
1

In [374]:
X_train_val1, X_test1, y_train_val1, y_test1 = train_test_split(X, y,test_size = 0.10, random_state=SEED)
X_train1, X_val1, y_train1, y_val1 = train_test_split(X_train_val1, y_train_val1,test_size = 0.30, random_state=SEED)

xgb_reg = xgboost.XGBRegressor(n_estimators=150, learning_rate=0.4, gamma=0, subsample=0.75,
                           colsample_bytree=1, max_depth=7,random_state=SEED)
xgb_reg.fit(X_train1, y_train1,eval_set=[(X_val1, y_val1)], early_stopping_rounds=EARLY_STOP_NUM)
y_pred = xgb_reg.predict(X_val1)
val_rmse = mean_squared_error(y_val1, y_pred,squared=False)  
print("Validation RMSE:", val_rmse) 
val_mse = mean_squared_error(y_val1, y_pred,squared=True)  
print("Validation MSE:", val_mse)

[0]	validation_0-rmse:0.00652
[1]	validation_0-rmse:0.00393
[2]	validation_0-rmse:0.00239
[3]	validation_0-rmse:0.00146
[4]	validation_0-rmse:0.00089
[5]	validation_0-rmse:0.00055
[6]	validation_0-rmse:0.00033
[7]	validation_0-rmse:0.00021
[8]	validation_0-rmse:0.00013
[9]	validation_0-rmse:0.00009
[10]	validation_0-rmse:0.00006
[11]	validation_0-rmse:0.00004
[12]	validation_0-rmse:0.00003
[13]	validation_0-rmse:0.00002
[14]	validation_0-rmse:0.00002
[15]	validation_0-rmse:0.00002
[16]	validation_0-rmse:0.00002
[17]	validation_0-rmse:0.00002
[18]	validation_0-rmse:0.00186
[19]	validation_0-rmse:0.00149
[20]	validation_0-rmse:0.00119
[21]	validation_0-rmse:0.00095
[22]	validation_0-rmse:0.00076
[23]	validation_0-rmse:0.00061
[24]	validation_0-rmse:0.00133
[25]	validation_0-rmse:0.00091
Validation RMSE: 1.8980462908625824e-05
Validation MSE: 3.6025797222572063e-10


C:\Users\Dell\anaconda3\Lib\site-packages\xgboost\sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


In [375]:
pred_test1 = xgb_reg.predict(X_test1)
pred_test1[:5]

array([-4.7492263e-06,  3.6526006e-05, -4.7492263e-06, -4.7492263e-06,
       -1.1729138e-05], dtype=float32)

In [376]:
pred_test1

array([-4.7492263e-06,  3.6526006e-05, -4.7492263e-06, -4.7492263e-06,
       -1.1729138e-05, -4.7492263e-06, -4.7492263e-06, -1.1729138e-05,
       -4.7492263e-06, -4.7492263e-06,  4.3505544e-05, -4.7492263e-06,
       -1.1729138e-05, -4.7492263e-06, -4.7492263e-06, -4.7492263e-06,
       -4.7492263e-06, -4.7492263e-06, -4.7492263e-06, -4.7492263e-06,
       -4.7492263e-06, -4.7492263e-06, -4.7492263e-06, -4.7492263e-06,
       -4.7492263e-06, -1.1729138e-05,  3.3066943e-01, -4.7492263e-06,
       -4.7492263e-06, -1.1729138e-05], dtype=float32)

In [377]:
X_test1.head(1)

SUBJID  RSRESP_Complete response  RSRESP_Partial response  RSRESP_Progressive disease  RSRESP_Stable disease  RSRESP_Unable to evaluate  DTHDY  PFSDYCR  PFSCR  DIAGMONS  B_METANM  LSSLD  LSCAT_New lesion  LSCAT_Non-target lesion  LSCAT_Target lesion  LBSTRESN
159     644                         0                        1                           0                      0                          0  289.0    289.0    1.0  1.803279       4.0  95.75                 0                        0                    1   173.048

import math

compdf1 = pd.DataFrame({'actual_AE': y_test1.values, 'predicted_AE': [math.ceil(i) for i in pred_test1]})


compdf1.sum()

 y_test1.values

pred_test1

compdf1['diff_AE'] = (compdf1['actual_AE'] - compdf1['predicted_AE']).abs()

compdf1['diff_AE'].hist()

## AESOC_2

In [378]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_2']

In [379]:
X_train_val1, X_test1, y_train_val1, y_test1 = train_test_split(X, y,test_size = 0.10, random_state=SEED)
X_train1, X_val1, y_train1, y_val1 = train_test_split(X_train_val1, y_train_val1,test_size = 0.30, random_state=SEED)

xgb_reg = xgboost.XGBRegressor(n_estimators=150, learning_rate=0.4, gamma=0, subsample=0.75,
                           colsample_bytree=1, max_depth=7,random_state=SEED)
xgb_reg.fit(X_train1, y_train1,eval_set=[(X_val1, y_val1)], early_stopping_rounds=EARLY_STOP_NUM)
y_pred = xgb_reg.predict(X_val1)
val_rmse = mean_squared_error(y_val1, y_pred,squared=False)  
print("Validation RMSE:", val_rmse) 
val_mse = mean_squared_error(y_val1, y_pred,squared=True)  
print("Validation MSE:", val_mse)

[0]	validation_0-rmse:0.11111
[1]	validation_0-rmse:0.11111
[2]	validation_0-rmse:0.11111
[3]	validation_0-rmse:0.11111
[4]	validation_0-rmse:0.11111
[5]	validation_0-rmse:0.11111
[6]	validation_0-rmse:0.11111
[7]	validation_0-rmse:0.11111
[8]	validation_0-rmse:0.11111
Validation RMSE: 0.1111111111111111
Validation MSE: 0.012345679012345678


C:\Users\Dell\anaconda3\Lib\site-packages\xgboost\sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


In [380]:
pred_test1 = xgb_reg.predict(X_test1)
pred_test1[:5]

array([0., 0., 0., 0., 0.], dtype=float32)

## AESOC_3

In [381]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_3']

In [382]:
X_train_val1, X_test1, y_train_val1, y_test1 = train_test_split(X, y,test_size = 0.10, random_state=SEED)
X_train1, X_val1, y_train1, y_val1 = train_test_split(X_train_val1, y_train_val1,test_size = 0.30, random_state=SEED)

xgb_reg = xgboost.XGBRegressor(n_estimators=150, learning_rate=0.4, gamma=0, subsample=0.75,
                           colsample_bytree=1, max_depth=7,random_state=SEED)
xgb_reg.fit(X_train1, y_train1,eval_set=[(X_val1, y_val1)], early_stopping_rounds=EARLY_STOP_NUM)
y_pred = xgb_reg.predict(X_val1)
val_rmse = mean_squared_error(y_val1, y_pred,squared=False)  
print("Validation RMSE:", val_rmse) 
val_mse = mean_squared_error(y_val1, y_pred,squared=True)  
print("Validation MSE:", val_mse)


[0]	validation_0-rmse:0.32015
[1]	validation_0-rmse:0.32313


C:\Users\Dell\anaconda3\Lib\site-packages\xgboost\sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(


[2]	validation_0-rmse:0.32087
[3]	validation_0-rmse:0.32005
[4]	validation_0-rmse:0.31887
[5]	validation_0-rmse:0.31822
[6]	validation_0-rmse:0.31824
[7]	validation_0-rmse:0.31880
[8]	validation_0-rmse:0.31833
[9]	validation_0-rmse:0.31979
[10]	validation_0-rmse:0.32081
[11]	validation_0-rmse:0.32044
[12]	validation_0-rmse:0.32020
Validation RMSE: 0.31821653462532096
Validation MSE: 0.10126176290894807


C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


In [383]:
pred_test1 = xgb_reg.predict(X_test1)
pred_test1[:5]

array([0.00278197, 0.00344007, 0.00278197, 0.00278197, 0.00278197],
      dtype=float32)

## AESOC_4

In [384]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_4']

In [385]:
X_train_val1, X_test1, y_train_val1, y_test1 = train_test_split(X, y,test_size = 0.10, random_state=SEED)
X_train1, X_val1, y_train1, y_val1 = train_test_split(X_train_val1, y_train_val1,test_size = 0.30, random_state=SEED)

xgb_reg = xgboost.XGBRegressor(n_estimators=150, learning_rate=0.4, gamma=0, subsample=0.75,
                           colsample_bytree=1, max_depth=7,random_state=SEED)
xgb_reg.fit(X_train1, y_train1,eval_set=[(X_val1, y_val1)], early_stopping_rounds=EARLY_STOP_NUM)
y_pred = xgb_reg.predict(X_val1)
val_rmse = mean_squared_error(y_val1, y_pred,squared=False)  
print("Validation RMSE:", val_rmse) 
val_mse = mean_squared_error(y_val1, y_pred,squared=True)  
print("Validation MSE:", val_mse)


[0]	validation_0-rmse:0.02944
[1]	validation_0-rmse:0.04305
[2]	validation_0-rmse:0.05607
[3]	validation_0-rmse:0.06693
[4]	validation_0-rmse:0.06670


C:\Users\Dell\anaconda3\Lib\site-packages\xgboost\sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(


[5]	validation_0-rmse:0.07557
[6]	validation_0-rmse:0.08267
[7]	validation_0-rmse:0.08836
[8]	validation_0-rmse:0.09291
Validation RMSE: 0.029444484315216027
Validation MSE: 0.0008669776565890026


C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


In [386]:
pred_test1 = xgb_reg.predict(X_test1)
pred_test1[:5]

array([0.01620868, 0.01620868, 0.01620868, 0.01620868, 0.01620868],
      dtype=float32)

## AESOC_5

In [387]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_5']

In [388]:
X_train_val1, X_test1, y_train_val1, y_test1 = train_test_split(X, y,test_size = 0.10, random_state=SEED)
X_train1, X_val1, y_train1, y_val1 = train_test_split(X_train_val1, y_train_val1,test_size = 0.30, random_state=SEED)

xgb_reg = xgboost.XGBRegressor(n_estimators=150, learning_rate=0.4, gamma=0, subsample=0.75,
                           colsample_bytree=1, max_depth=7,random_state=SEED)
xgb_reg.fit(X_train1, y_train1,eval_set=[(X_val1, y_val1)], early_stopping_rounds=EARLY_STOP_NUM)
y_pred = xgb_reg.predict(X_val1)
val_rmse = mean_squared_error(y_val1, y_pred,squared=False)  
print("Validation RMSE:", val_rmse) 
val_mse = mean_squared_error(y_val1, y_pred,squared=True)  
print("Validation MSE:", val_mse)


[0]	validation_0-rmse:0.53132
[1]	validation_0-rmse:0.55591
[2]	validation_0-rmse:0.55304
[3]	validation_0-rmse:0.57742
[4]	validation_0-rmse:0.58366
[5]	validation_0-rmse:0.57944
[6]	validation_0-rmse:0.57967
[7]	validation_0-rmse:0.58359


C:\Users\Dell\anaconda3\Lib\site-packages\xgboost\sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(


[8]	validation_0-rmse:0.58065
Validation RMSE: 0.5313163398004973
Validation MSE: 0.28229705293899754


C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


In [389]:
pred_test1 = xgb_reg.predict(X_test1)
pred_test1[:5]

array([0.08453661, 0.08453661, 0.08453661, 0.08610752, 0.08453661],
      dtype=float32)

## AESOC_6

In [390]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_6']

In [391]:
X_train_val1, X_test1, y_train_val1, y_test1 = train_test_split(X, y,test_size = 0.10, random_state=SEED)
X_train1, X_val1, y_train1, y_val1 = train_test_split(X_train_val1, y_train_val1,test_size = 0.30, random_state=SEED)

xgb_reg = xgboost.XGBRegressor(n_estimators=150, learning_rate=0.4, gamma=0, subsample=0.75,
                           colsample_bytree=1, max_depth=7,random_state=SEED)
xgb_reg.fit(X_train1, y_train1,eval_set=[(X_val1, y_val1)], early_stopping_rounds=EARLY_STOP_NUM)
y_pred = xgb_reg.predict(X_val1)
val_rmse = mean_squared_error(y_val1, y_pred,squared=False)  
print("Validation RMSE:", val_rmse) 
val_mse = mean_squared_error(y_val1, y_pred,squared=True)  
print("Validation MSE:", val_mse)

[0]	validation_0-rmse:0.15809
[1]	validation_0-rmse:0.15849
[2]	validation_0-rmse:0.16913
[3]	validation_0-rmse:0.17935
[4]	validation_0-rmse:0.18035
[5]	validation_0-rmse:0.18596
[6]	validation_0-rmse:0.18882
[7]	validation_0-rmse:0.18865
Validation RMSE: 0.15809026225356668
Validation MSE: 0.024992531019401486


C:\Users\Dell\anaconda3\Lib\site-packages\xgboost\sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


In [392]:
pred_test1 = xgb_reg.predict(X_test1)
pred_test1[:5]

array([0.02352151, 0.02508961, 0.02311828, 0.02311828, 0.02280873],
      dtype=float32)

## AESOC_7

In [393]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_7']

In [394]:
X_train_val1, X_test1, y_train_val1, y_test1 = train_test_split(X, y,test_size = 0.10, random_state=SEED)
X_train1, X_val1, y_train1, y_val1 = train_test_split(X_train_val1, y_train_val1,test_size = 0.30, random_state=SEED)

xgb_reg = xgboost.XGBRegressor(n_estimators=150, learning_rate=0.4, gamma=0, subsample=0.75,
                           colsample_bytree=1, max_depth=7,random_state=SEED)
xgb_reg.fit(X_train1, y_train1,eval_set=[(X_val1, y_val1)], early_stopping_rounds=EARLY_STOP_NUM)
y_pred = xgb_reg.predict(X_val1)
val_rmse = mean_squared_error(y_val1, y_pred,squared=False)  
print("Validation RMSE:", val_rmse) 
val_mse = mean_squared_error(y_val1, y_pred,squared=True)  
print("Validation MSE:", val_mse)


C:\Users\Dell\anaconda3\Lib\site-packages\xgboost\sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(


[0]	validation_0-rmse:0.10578
[1]	validation_0-rmse:0.10547
[2]	validation_0-rmse:0.13201
[3]	validation_0-rmse:0.13237
[4]	validation_0-rmse:0.13870
[5]	validation_0-rmse:0.13536
[6]	validation_0-rmse:0.13382
[7]	validation_0-rmse:0.13303
[8]	validation_0-rmse:0.13288
[9]	validation_0-rmse:0.13309
Validation RMSE: 0.10546826279220896
Validation MSE: 0.011123554456406448


C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


In [395]:
pred_test1 = xgb_reg.predict(X_test1)
pred_test1[:5]

array([0.00388145, 0.00388145, 0.00388145, 0.00388145, 0.00388145],
      dtype=float32)

## AESOC_8

In [396]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_8']

In [397]:
X_train_val1, X_test1, y_train_val1, y_test1 = train_test_split(X, y,test_size = 0.10, random_state=SEED)
X_train1, X_val1, y_train1, y_val1 = train_test_split(X_train_val1, y_train_val1,test_size = 0.30, random_state=SEED)

xgb_reg = xgboost.XGBRegressor(n_estimators=150, learning_rate=0.4, gamma=0, subsample=0.75,
                           colsample_bytree=1, max_depth=7,random_state=SEED)
xgb_reg.fit(X_train1, y_train1,eval_set=[(X_val1, y_val1)], early_stopping_rounds=EARLY_STOP_NUM)
y_pred = xgb_reg.predict(X_val1)
val_rmse = mean_squared_error(y_val1, y_pred,squared=False)  
print("Validation RMSE:", val_rmse) 
val_mse = mean_squared_error(y_val1, y_pred,squared=True)  
print("Validation MSE:", val_mse)


[0]	validation_0-rmse:0.00000
[1]	validation_0-rmse:0.00000
[2]	validation_0-rmse:0.00000
[3]	validation_0-rmse:0.00000
[4]	validation_0-rmse:0.00000
[5]	validation_0-rmse:0.00000
[6]	validation_0-rmse:0.00000
[7]	validation_0-rmse:0.00000
Validation RMSE: 0.0
Validation MSE: 0.0


C:\Users\Dell\anaconda3\Lib\site-packages\xgboost\sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


In [398]:
pred_test1 = xgb_reg.predict(X_test1)
pred_test1[:5]

array([0., 0., 0., 0., 0.], dtype=float32)

## AESOC_9

In [399]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_9']

In [401]:
X_train_val1, X_test1, y_train_val1, y_test1 = train_test_split(X, y,test_size = 0.10, random_state=SEED)
X_train1, X_val1, y_train1, y_val1 = train_test_split(X_train_val1, y_train_val1,test_size = 0.30, random_state=SEED)

xgb_reg = xgboost.XGBRegressor(n_estimators=150, learning_rate=0.4, gamma=0, subsample=0.75,
                           colsample_bytree=1, max_depth=7,random_state=SEED)
xgb_reg.fit(X_train1, y_train1,eval_set=[(X_val1, y_val1)], early_stopping_rounds=EARLY_STOP_NUM)
y_pred = xgb_reg.predict(X_val1)
val_rmse = mean_squared_error(y_val1, y_pred,squared=False)  
print("Validation RMSE:", val_rmse) 
val_mse = mean_squared_error(y_val1, y_pred,squared=True)  
print("Validation MSE:", val_mse)


[0]	validation_0-rmse:0.02293
[1]	validation_0-rmse:0.02264
[2]	validation_0-rmse:0.04028
[3]	validation_0-rmse:0.04022
[4]	validation_0-rmse:0.04019
[5]	validation_0-rmse:0.04017
[6]	validation_0-rmse:0.04015
[7]	validation_0-rmse:0.05434
[8]	validation_0-rmse:0.06570
[9]	validation_0-rmse:0.07478
Validation RMSE: 0.022639679576147556
Validation MSE: 0.0005125550913106328


C:\Users\Dell\anaconda3\Lib\site-packages\xgboost\sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


In [ ]:
pred_test1 = xgb_reg.predict(X_test1)
pred_test1[:5]

# Feature Importance

In [ ]:
# Feature importance based on different metrics
importance_weight = xgb_reg.get_booster().get_score(importance_type='weight')
importance_gain = xgb_reg.get_booster().get_score(importance_type='gain')
importance_cover = xgb_reg.get_booster().get_score(importance_type='cover')

# Converting to DataFrame for better visualization
importance_weight_df = pd.DataFrame(list(importance_weight.items()), columns=['Feature', 'Weight']).sort_values(by='Weight', ascending=False)
importance_gain_df = pd.DataFrame(list(importance_gain.items()), columns=['Feature', 'Gain']).sort_values(by='Gain', ascending=False)
importance_cover_df = pd.DataFrame(list(importance_cover.items()), columns=['Feature', 'Cover']).sort_values(by='Cover', ascending=False)

importance_weight_df.head(), importance_gain_df.head(), importance_cover_df.head()

In [ ]:
def plot_importance(importance_dict, title,num_rows):
    importance_df = pd.DataFrame(list(importance_dict.items()), columns=['Feature', 'Score'])
    importance_df = importance_df.sort_values(by='Score', ascending=False)
    importance_df.iloc[:num_rows].plot(kind='barh', x='Feature', y='Score', legend=False, title=title)
    plt.ylabel('Score')
    plt.show()

# Plotting
plot_importance(importance_weight, 'Feature Importance by Weight',10)
plot_importance(importance_gain, 'Feature Importance by Gain',10)
plot_importance(importance_cover, 'Feature Importance by Cover',10)


!pip install shap

In [ ]:
import shap

In [ ]:
explainer = shap.TreeExplainer(xgb_reg)
shap_values = explainer.shap_values(X)

In [ ]:
shap.summary_plot(shap_values, X)

## AESOC_10

In [402]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_10']

In [403]:
X_train_val1, X_test1, y_train_val1, y_test1 = train_test_split(X, y,test_size = 0.10, random_state=SEED)
X_train1, X_val1, y_train1, y_val1 = train_test_split(X_train_val1, y_train_val1,test_size = 0.30, random_state=SEED)

xgb_reg = xgboost.XGBRegressor(n_estimators=150, learning_rate=0.4, gamma=0, subsample=0.75,
                           colsample_bytree=1, max_depth=7,random_state=SEED)
xgb_reg.fit(X_train1, y_train1,eval_set=[(X_val1, y_val1)], early_stopping_rounds=EARLY_STOP_NUM)
y_pred = xgb_reg.predict(X_val1)
val_rmse = mean_squared_error(y_val1, y_pred,squared=False)  
print("Validation RMSE:", val_rmse) 
val_mse = mean_squared_error(y_val1, y_pred,squared=True)  
print("Validation MSE:", val_mse)


[0]	validation_0-rmse:4.33676
[1]	validation_0-rmse:4.64248
[2]	validation_0-rmse:4.77424
[3]	validation_0-rmse:4.99511
[4]	validation_0-rmse:4.98244
[5]	validation_0-rmse:5.00230
[6]	validation_0-rmse:4.99007
[7]	validation_0-rmse:4.96945
[8]	validation_0-rmse:4.94602
Validation RMSE: 4.3367568316436005
Validation MSE: 18.807459816807437


C:\Users\Dell\anaconda3\Lib\site-packages\xgboost\sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


In [404]:
pred_test1 = xgb_reg.predict(X_test1)
pred_test1[:5]

array([4.377916 , 3.4048388, 3.4048388, 4.377916 , 4.377916 ],
      dtype=float32)

# Feature Importance

In [ ]:
# Feature importance based on different metrics
importance_weight = xgb_reg.get_booster().get_score(importance_type='weight')
importance_gain = xgb_reg.get_booster().get_score(importance_type='gain')
importance_cover = xgb_reg.get_booster().get_score(importance_type='cover')

# Converting to DataFrame for better visualization
importance_weight_df = pd.DataFrame(list(importance_weight.items()), columns=['Feature', 'Weight']).sort_values(by='Weight', ascending=False)
importance_gain_df = pd.DataFrame(list(importance_gain.items()), columns=['Feature', 'Gain']).sort_values(by='Gain', ascending=False)
importance_cover_df = pd.DataFrame(list(importance_cover.items()), columns=['Feature', 'Cover']).sort_values(by='Cover', ascending=False)

importance_weight_df.head(), importance_gain_df.head(), importance_cover_df.head()

In [ ]:
def plot_importance(importance_dict, title,num_rows):
    importance_df = pd.DataFrame(list(importance_dict.items()), columns=['Feature', 'Score'])
    importance_df = importance_df.sort_values(by='Score', ascending=False)
    importance_df.iloc[:num_rows].plot(kind='barh', x='Feature', y='Score', legend=False, title=title)
    plt.ylabel('Score')
    plt.show()

# Plotting
plot_importance(importance_weight, 'Feature Importance by Weight',10)
plot_importance(importance_gain, 'Feature Importance by Gain',10)
plot_importance(importance_cover, 'Feature Importance by Cover',10)


!pip install shap

In [ ]:
import shap

In [ ]:
explainer = shap.TreeExplainer(xgb_reg)
shap_values = explainer.shap_values(X)

In [ ]:
shap.summary_plot(shap_values, X)

## Dropping few columns to reduce overfitting

In [ ]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['PFSCR','AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration','B_METANM','RSRESP_Partial response','RSRESP_Complete response','RSRESP_Progressive disease','RSRESP_Unable to evaluate','RSRESP_Stable disease'])
y = numeric_columns['AESOC_10']

In [ ]:
X_train_val1, X_test1, y_train_val1, y_test1 = train_test_split(X, y,test_size = 0.10, random_state=SEED)
X_train1, X_val1, y_train1, y_val1 = train_test_split(X_train_val1, y_train_val1,test_size = 0.30, random_state=SEED)

xgb_reg = xgboost.XGBRegressor(n_estimators=150, learning_rate=0.4, gamma=0, subsample=0.75,
                           colsample_bytree=1, max_depth=7,random_state=SEED)
xgb_reg.fit(X_train1, y_train1,eval_set=[(X_val1, y_val1)], early_stopping_rounds=EARLY_STOP_NUM)
y_pred = xgb_reg.predict(X_val1)
val_rmse = mean_squared_error(y_val1, y_pred,squared=False)  
print("Validation RMSE:", val_rmse) 
val_mse = mean_squared_error(y_val1, y_pred,squared=True)  
print("Validation MSE:", val_mse)


## No change in the values

In [ ]:
# Feature importance based on different metrics
importance_weight = xgb_reg.get_booster().get_score(importance_type='weight')
importance_gain = xgb_reg.get_booster().get_score(importance_type='gain')
importance_cover = xgb_reg.get_booster().get_score(importance_type='cover')

# Converting to DataFrame for better visualization
importance_weight_df = pd.DataFrame(list(importance_weight.items()), columns=['Feature', 'Weight']).sort_values(by='Weight', ascending=False)
importance_gain_df = pd.DataFrame(list(importance_gain.items()), columns=['Feature', 'Gain']).sort_values(by='Gain', ascending=False)
importance_cover_df = pd.DataFrame(list(importance_cover.items()), columns=['Feature', 'Cover']).sort_values(by='Cover', ascending=False)

importance_weight_df.head(), importance_gain_df.head(), importance_cover_df.head()

In [ ]:
def plot_importance(importance_dict, title,num_rows):
    importance_df = pd.DataFrame(list(importance_dict.items()), columns=['Feature', 'Score'])
    importance_df = importance_df.sort_values(by='Score', ascending=False)
    importance_df.iloc[:num_rows].plot(kind='barh', x='Feature', y='Score', legend=False, title=title)
    plt.ylabel('Score')
    plt.show()

# Plotting
plot_importance(importance_weight, 'Feature Importance by Weight',10)
plot_importance(importance_gain, 'Feature Importance by Gain',10)
plot_importance(importance_cover, 'Feature Importance by Cover',10)


## Hyperparameters

In [ ]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

# Define dependent and independent variabl

# Split data
X_train_val1, X_test1, y_train_val1, y_test1 = train_test_split(X, y, test_size=0.10, random_state=SEED)
X_train1, X_val1, y_train1, y_val1 = train_test_split(X_train_val1, y_train_val1, test_size=0.30, random_state=SEED)

# XGBoost Regressor with tuned hyperparameters
xgb_reg = xgb.XGBRegressor(
    n_estimators=500,              # Increase number of trees
    learning_rate=0.01,            # Reduce learning rate
    gamma=0,                       # Control overfitting (higher values prevent overfitting)
    subsample=0.8,                 # Subsample ratio of the training instance
    colsample_bytree=0.8,          # Subsample ratio of columns when constructing each tree
    max_depth=5,                   # Maximum depth of a tree
    alpha=0.1,                     # L1 regularization term on weights
    lambda_=0.1,                   # L2 regularization term on weights
    random_state=SEED
)

# Fit model with early stopping
xgb_reg.fit(
    X_train1, y_train1,
    eval_set=[(X_val1, y_val1)],
    early_stopping_rounds=50,      # Use early stopping
    verbose=True
)

# Predict and evaluate
y_pred = xgb_reg.predict(X_val1)
val_rmse = mean_squared_error(y_val1, y_pred,squared=False)  
print("Validation RMSE:", val_rmse) 
val_mse = mean_squared_error(y_val1, y_pred,squared=True)  
print("Validation MSE:", val_mse)

# Predict on test set
pred_test1 = xgb_reg.predict(X_test1)
pred_test1[:5]


from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = {
    'n_estimators': [500, 1000],
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [3, 5, 7],
    'subsample': [0.6, 0.8, 1.0],
    'colsample_bytree': [0.6, 0.8, 1.0],
    'gamma': [0, 0.1, 0.2],
    'alpha': [0, 0.1, 0.5],
    'lambda': [0, 0.1, 0.5]
}

# Initialize XGBoost regressor
xgb_reg = xgb.XGBRegressor(random_state=SEED)

# Initialize GridSearchCV
grid_search = GridSearchCV(estimator=xgb_reg, param_grid=param_grid, cv=3, scoring='neg_mean_squared_error', verbose=1, n_jobs=-1)

# Fit GridSearchCV
grid_search.fit(X_train_val1, y_train_val1)

# Print the best parameters and the best score
print("Best parameters found: ", grid_search.best_params_)
print("Lowest RMSE found: ", (-grid_search.best_score_) ** 0.5)


# Extract the best parameters from the grid search
best_params = grid_search.best_params_

# Initialize XGBoost regressor with the best parameters
xgb_reg_best = xgb.XGBRegressor(
    n_estimators=best_params['n_estimators'],
    learning_rate=best_params['learning_rate'],
    max_depth=best_params['max_depth'],
    subsample=best_params['subsample'],
    colsample_bytree=best_params['colsample_bytree'],
    gamma=best_params['gamma'],
    alpha=best_params['alpha'],
    lambda_=best_params['lambda'],
    random_state=SEED
)

# Fit the model with the best parameters
xgb_reg_best.fit(
    X_train1, y_train1,
    eval_set=[(X_val1, y_val1)],
    early_stopping_rounds=50,
    verbose=True
)

# Predict and evaluate
y_pred = xgb_reg_best.predict(X_val1)
val_error = mean_squared_error(y_val1, y_pred, squared=False)
print("Validation RMSE with best parameters:", val_error)

# Predict on test set
pred_test1 = xgb_reg_best.predict(X_test1)
pred_test1[:5]


from sklearn.model_selection import cross_val_score

# Perform k-fold cross-validation
cv_scores = cross_val_score(xgb_reg_best, X_train_val1, y_train_val1, cv=5, scoring='neg_mean_squared_error')

# Convert to RMSE
rmse_scores = (-cv_scores) ** 0.5
print("Cross-validated RMSE scores:", rmse_scores)
print("Mean RMSE:", rmse_scores.mean())
print("Standard Deviation RMSE:", rmse_scores.std())


## AESOC_11

In [405]:
# Define dependent and independent variables
X = numeric_columns.drop(columns=['AESEVCD','AESOC_1','AESOC_2','AESOC_3','AESOC_4','AESOC_5','AESOC_6','AESOC_7','AESOC_8','AESOC_9','AESOC_10','AESOC_11','Duration'])
y = numeric_columns['AESOC_11']

In [406]:
X_train_val1, X_test1, y_train_val1, y_test1 = train_test_split(X, y,test_size = 0.10, random_state=SEED)
X_train1, X_val1, y_train1, y_val1 = train_test_split(X_train_val1, y_train_val1,test_size = 0.30, random_state=SEED)

xgb_reg = xgboost.XGBRegressor(n_estimators=150, learning_rate=0.4, gamma=0, subsample=0.75,
                           colsample_bytree=1, max_depth=7,random_state=SEED)
xgb_reg.fit(X_train1, y_train1,eval_set=[(X_val1, y_val1)], early_stopping_rounds=EARLY_STOP_NUM)
y_pred = xgb_reg.predict(X_val1)
val_rmse = mean_squared_error(y_val1, y_pred,squared=False)  
print("Validation RMSE:", val_rmse) 
val_mse = mean_squared_error(y_val1, y_pred,squared=True)  
print("Validation MSE:", val_mse)


[0]	validation_0-rmse:0.47106
[1]	validation_0-rmse:0.47517
[2]	validation_0-rmse:0.47572
[3]	validation_0-rmse:0.47706
[4]	validation_0-rmse:0.47902
[5]	validation_0-rmse:0.47890
[6]	validation_0-rmse:0.48084
[7]	validation_0-rmse:0.48199
Validation RMSE: 0.47105846519154804
Validation MSE: 0.22189607762861688


C:\Users\Dell\anaconda3\Lib\site-packages\xgboost\sklearn.py:889: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(
C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


In [ ]:
pred_test1 = xgb_reg.predict(X_test1)
pred_test1[:5]

# Feature Importance

In [ ]:
# Feature importance based on different metrics
importance_weight = xgb_reg.get_booster().get_score(importance_type='weight')
importance_gain = xgb_reg.get_booster().get_score(importance_type='gain')
importance_cover = xgb_reg.get_booster().get_score(importance_type='cover')

# Converting to DataFrame for better visualization
importance_weight_df = pd.DataFrame(list(importance_weight.items()), columns=['Feature', 'Weight']).sort_values(by='Weight', ascending=False)
importance_gain_df = pd.DataFrame(list(importance_gain.items()), columns=['Feature', 'Gain']).sort_values(by='Gain', ascending=False)
importance_cover_df = pd.DataFrame(list(importance_cover.items()), columns=['Feature', 'Cover']).sort_values(by='Cover', ascending=False)

importance_weight_df.head(), importance_gain_df.head(), importance_cover_df.head()

In [ ]:
def plot_importance(importance_dict, title,num_rows):
    importance_df = pd.DataFrame(list(importance_dict.items()), columns=['Feature', 'Score'])
    importance_df = importance_df.sort_values(by='Score', ascending=False)
    importance_df.iloc[:num_rows].plot(kind='barh', x='Feature', y='Score', legend=False, title=title)
    plt.ylabel('Score')
    plt.show()

# Plotting
plot_importance(importance_weight, 'Feature Importance by Weight',10)
plot_importance(importance_gain, 'Feature Importance by Gain',10)
plot_importance(importance_cover, 'Feature Importance by Cover',10)


!pip install shap

In [ ]:
import shap

In [ ]:
explainer = shap.TreeExplainer(xgb_reg)
shap_values = explainer.shap_values(X)

In [ ]:
shap.summary_plot(shap_values, X)